### PR TITLE
Update README to include instructions on how to run tests

### LINKED ISSUE #29: How to run tests
I am trying to execute the tests via `cabal new-test` as well as `stack test`. 
On the former, the tests hang indefinitely long, on the latter 30/31 tests fail.

I am thinking I may be doing something wrong, what is necessary to run the tests?

### PR DESCRIPTION
**Pull request by fendor**
Includes more detailed instructions on how to run the tests.

Closes #29

### CODE REVIEW

**Comment by bubba** [comment]
Thanks! I'm going to check if it works with HIE 8.6.3 and then update .travis.yml first

**Comment by fendor** [comment]
Any news?

**Comment by bubba** [comment]
Sorry forgot about this, thanks!

**Comment by alanz** [comment]
@bubba given the windows problem with 8.6.3, this should probably be updated to require 8.6.4

**Comment by bubba** [comment]
I’ve updated it to say just use whatever is on the nightly stack.yaml

**Pull request merged**
